title: "Baykal Media"
description: "Documentary, cinematic photography"
url: "https://www.baykalmedia.com"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "air"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: Baykal Media
  links:
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/yourhandle"
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://facebook.com/yourhandle"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:hello@baykalmedia.com"
